### ISSUE TITLE
Where is it? bca_dict_trained.csv 

### ISSUE THREAD

**Issue by gazzola** [Farahn/Liguistic-Complexity#1]
In your code you point to the file '' trainedbcamodel / bca_dict_trained.csv '". But, there is neither this folder nor this file in your code. What would they be? Would CCS.csv be downloaded at the address you passed?
Why did you use the START parameter in the dictionary?
Because, using a base I get the following error

KeyError                                  Traceback (most recent call last)
<ipython-input-12-32cb5a9633b9> in <module>()
----> 1 X_test_ = read_test_set(df_test, dictionary, SEQUENCE_LEN_D = SEQUENCE_LENGTH_D, SEQUENCE_LEN = SEQUENCE_LENGTH)

dataUtilsbca.py in read_test_set(df_test, dictionary, SEQUENCE_LEN_D, SEQUENCE_LEN, BATCH_SIZE)
     84             print(x)
     85             data = []
---> 86             data.append(dictionary['START'])
     87             for word in x:
     88                 if word in dictionary:

KeyError: 'START'

**Comment by Farahn** [comment]
Hi, I recently moved the dictionary and trained models, I will update the links today. The error is being generated since the dict in empty, and the "START" token is not in the dictionary. The "START" token is used to indicate the start of sentence.

**Comment by gazzola** [comment]
Thanks Farahn, I'm waiting. I am ancious in running your experiments as soon as you are working with Portuguese texts, but with more than 100 words.

**Comment by Farahn** [comment]
I have updated the link and the TF version to 1.8. If you download the model folder, it has the dict and pre-trained models. Let me know if there are any issues running it. I have just trained on English texts, but you can retrain with Portugese texts using the original code. Thanks!
